version: '3.8'

services:
  postgresql_dev:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=legaplan
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
