name: "Next CI"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build-and-push:
    name: "Build and Push"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t killercf/legaplan.web:${{ steps.generate_sha.outputs.sha }} .

      - name: Log into container register
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to container register
        run: |
          docker push killercf/legaplan.web:${{ steps.generate_sha.outputs.sha }}
          docker tag killercf/legaplan.web:${{ steps.generate_sha.outputs.sha }} killercf/legaplan.web:latest
          docker push killercf/legaplan.web:latest
